### ISSUE TITLE
TZXduino V1.20.1 not working

### ISSUE THREAD

**Issue by Snocksman** [arananet/TzxDuino-Reloaded#5]
Hi !

I downloaded TZXduino V1.20.1 from here: [https://github.com/stripwax/TZXDuino/releases/tag/TZXDuino1.20.1](url) and flashed it to my TZXduino reloaded V1.5, but after flashing the OLED Display stays off. Whats wrong there ?

If i flash the Maxduino Firmware it´s working fine, so it´s nothing wrong with the Hardware itself...

**Comment by arananet** [comment]
mmm if the OLED does not work with the older firmware it might be related to the hardware id set up for the OLED screen on that version. There are some projects to get the current hardware id from the oled screen in order to then set up the id correctly on the old code. 

Also take a look to the display.ino file... the oled address is commented, that could explain why is not working.

  #define OLED_address   0x3C //0x3C or 0x3D

On any case, this is not related with my hardware, but firmware instead.
